// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';

const SUPABASE_URL = "https://uixuqzgzmtlrrfogfrgp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVpeHVxemd6bXRscnJmb2dmcmdwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTcwNTY1ODcsImV4cCI6MjA3MjYzMjU4N30.XSth0JtTaE0iBfRjshbYdbKZphyVczQj32sNmdBUtWk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);